# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "digitalpardoe-rflickr"
  s.version = "2.0.0.pre.1"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Pardoe"]
  s.date = "2013-08-12"
  s.description = "rFlickr is a clone of the original RubyForge based rflickr, a Ruby implementation of the Flickr API. It includes a faithful albeit old reproduction of the published API."
  s.email = "contact@digitalpardoe.co.uk"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    "Gemfile",
    "README.md",
    "Rakefile",
    "VERSION",
    "digitalpardoe-rflickr.gemspec",
    "lib/flickr.rb",
    "lib/flickr/api.rb",
    "lib/flickr/interaction/flickr_api_request.rb",
    "lib/flickr/interaction/request.rb",
    "spec/api/activity_spec.rb",
    "spec/api/api_spec.rb",
    "spec/api/auth_spec.rb",
    "spec/api/blogs_spec.rb",
    "spec/api/collections_spec.rb",
    "spec/api/commons_spec.rb",
    "spec/api/contacts_spec.rb",
    "spec/api/favorites_spec.rb",
    "spec/api/groups/members_spec.rb",
    "spec/config/api.example.yml",
    "spec/flickr_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/digitalpardoe/rflickr"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "rFlickr is a Ruby interface to the Flickr API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, ["~> 1.8.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<ZenTest>, [">= 0"])
    else
      s.add_dependency(%q<json>, ["~> 1.8.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<ZenTest>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, ["~> 1.8.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<ZenTest>, [">= 0"])
  end
end

