# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rflickr"
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Pardoe"]
  s.date = "2013-08-07"
  s.description = "rFlickr is a clone of the original RubyForge based rflickr, a Ruby implementation of the Flickr API. It includes a faithful albeit old reproduction of the published API."
  s.email = "contact@digitalpardoe.co.uk"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "README",
    "Rakefile",
    "VERSION",
    "lib/api/base/activity.rb",
    "lib/api/base/auth.rb",
    "lib/api/base/blogs.rb",
    "lib/api/base/collections.rb",
    "lib/api/base/commons.rb",
    "lib/api/base/contacts.rb",
    "lib/api/base/favorites.rb",
    "lib/api/base/groups.rb",
    "lib/api/base/groups/members.rb",
    "lib/api/base/groups/pools.rb",
    "lib/api/base/interestingness.rb",
    "lib/api/base/machinetags.rb",
    "lib/api/base/panda.rb",
    "lib/api/base/people.rb",
    "lib/api/base/photos.rb",
    "lib/api/base/photos/comments.rb",
    "lib/api/base/photos/geo.rb",
    "lib/api/base/photos/licenses.rb",
    "lib/api/base/photos/notes.rb",
    "lib/api/base/photos/transform.rb",
    "lib/api/base/photos/upload.rb",
    "lib/api/base/photosets.rb",
    "lib/api/base/photosets/comments.rb",
    "lib/api/base/places.rb",
    "lib/api/base/prefs.rb",
    "lib/api/base/reflection.rb",
    "lib/api/base/tags.rb",
    "lib/api/base/test.rb",
    "lib/api/base/urls.rb",
    "lib/api/ext/auth.rb",
    "lib/core/api_base.rb",
    "lib/core/interaction/flickr_api_request.rb",
    "lib/core/interaction/request.rb",
    "lib/flickr.rb",
    "rflickr.gemspec",
    "spec/api/activity_spec.rb",
    "spec/api/auth_spec.rb",
    "spec/api/blogs_spec.rb",
    "spec/api/collections_spec.rb",
    "spec/api/commons_spec.rb",
    "spec/api/contacts_spec.rb",
    "spec/api/favorites_spec.rb",
    "spec/api/groups/members_spec.rb",
    "spec/config/api.example.yml",
    "spec/flickr_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/digitalpardoe/rflickr"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "rFlickr is a Ruby interface to the Flickr API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

